### ISSUE TITLE
Got a message "odd number today" after I requested skipping

### ISSUE THREAD

**Issue by vpavlenko** [marenbeam/pairing-bot#7]
![2020-01-23_10-32-02](https://user-images.githubusercontent.com/1491908/72998297-9c68f100-3dcb-11ea-8718-15572d8186b6.png)

**Comment by marenbeam** [comment]
Thank you so much for submitting this! It’s definitely unexpected behavior. I’ll look into it tonight.

**Comment by marenbeam** [comment]
@vpavlenko Were scheduled for pairing on Wednesdays when this happened?

**Comment by vpavlenko** [comment]
@marenbeam I was scheduled for Wednesday, but I skipped it before the cutoff time. Here's a bit bigger chunk of history (probably doesn't add information):

![2020-01-24_12-26-44](https://user-images.githubusercontent.com/1491908/73089761-ed004d00-3ea4-11ea-91f8-8834523d38eb.png)

**Comment by marenbeam** [comment]
Definitely adds information — thank you!

**Comment by marenbeam** [comment]
I wasn't able to confirm this myself, nor was I able to find anything helpful in the logs, and I haven't heard other reports of people having this problem. Closing for now, and hoping this gets resolved in v2, but please feel free to reopen if it continues happening, someone has more info, or there are more reports of the same problem happening :slightly_smiling_face:
